# Generated by Django 5.1.6 on 2025-03-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
